### PR TITLE
HACK: manually update vega-lite.js, vega.js, and vega-embed.js URLs (…

### PR DESCRIPTION
**Pull request by eocarragain**
…already fixed in altair master)

The examples are currently broken. This aligns the URLs with the 834df80b94456710d6a2eb8b9d7f9a3c8b7a13df commit on altair master.

### CODE REVIEW

**Comment by jakevdp** [comment]
Thanks! The current Altair master uses vega-lite version 1.2.1 ([recorded here](https://github.com/altair-viz/altair/blob/master/altair/schema/_vegalite_version.py)). Could you use that URL instead?

**Comment by eocarragain** [comment]
Altair master now defaults to the 1.3.1 URL (in urls.py). Would it make more sense to simply bump _vegalite_version.py to 1.3.1?

Let me know either way & I'll either update this pull request to use 1.2.1 or create a new one to update _vegalite_version.py. Cheers

**Comment by jakevdp** [comment]
Oh, that's a problem. The URL in urls.py should be changed to use 1.2.1 as well. The Altair API currently in master is built to reflect 1.2.1.

**Comment by jakevdp** [comment]
OK, I fixed the URL in ``urls.py``: https://github.com/altair-viz/altair/commit/79a0031a55053a6ee4e50dc84873e54aa9fad6e8

**Comment by jakevdp** [comment]
Just some more info: the URL in ``vegalite_version.py`` is automatically written when the Altair API is generated from the vega-lite schema, so that is always the correct version to use.

**Comment by eocarragain** [comment]
Thanks. Good to know re vegalite_version.py being an automated process. I'm closing this PR in favour of https://github.com/altair-viz/altair-viz.github.io/pull/5 . I managed to mess up the other branch in an failed attempt to git revert the previous commit :)

**Pull request closed without merging**
